- name: Test Connection Playbook
  gather_facts: false
  become: yes
  hosts: all 
  tasks:
  - name: Check hostname
    shell:  "hostname"
  - name: Check time
    shell:  "date -R"
  - name: show vars
    shell:  echo "{{ test_var }}"
